version: "3.9"

services
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "80:80/tcp"
    environment:
      TZ: "Europe/Tallinn"
      WEBPASSWORD: "Passw0rd"
    volumes:
    - pihole_etc:/etc/pihole
    - dnsmasq:/etc/dnsmasq.d
volumes:
      pihole_etc:
      dnsmasq:
