version: "3.9"

services
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
    - "8080-8080"
    volumes:
    - dozzle-data:/data
    - /var/run/docker.sock:/var/run/docker.sock

volumes:
      dozzle_data:
